--- 
repository:
application:

user:
group:

ruby_loader:
deploy_ruby: ree
app_ruby:

branches: [ production staging master ]
branch_regex: ^

chef_path: 

notify:
  email:
    recipients: 
    - 
  campfire:
    account:
    room:
    email:
    token:
  airbrake:
    api_key:
